### ISSUE TITLE
Message/thread actions menu

### ISSUE THREAD

**Issue by flowbe** [Infomaniak/ios-kMail#105]
### To do
- [x] Delete (#159)
- [x] Reply / reply all / forward (#161)
- [x] Archive (#161)
- [x] Mark as read / unread (#159)
- [x] Move (#173)
- [ ] Postpone
- [x] Spam / no spam (#169)
- [x] Block sender (#169)
- [x] Phishing (#169)
- [ ] Print
- [ ] Save as PDF
- [ ] Open in
- [ ] Create rule
- [x] Report display issue (#258)
- [ ] Edit menu
